home/urls.py
from django.urls import path
from . import views

app_name = "home"

urlpatterns = [
    path('', views.home, name = "home"),
    path('info/', views.info, name="info"),
    path('profile/', views.get_profile_info, name="myAccount"),
    path('profile/save/', views.save_changed_profile_info, name="myAccountInfo"),
    path('list_of_tutors/', views.teachers_list, name="teacherList"),
    path('list_of_work/', views.study_work_list, name="workList"),
    path('create/tutor/', views.create_tutor, name="createTutor"),
    path('create/study_work/', views.create_workload, name="createWork"),
    path('delete/study_work/<int:id>', views.delete_workload, name='deleteWork'),
    # path("<int:id>/", views.index, name="index"),
] 
# + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

workload/urls.py
# from django.conf.urls import url
from django.urls import include, path

from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.contrib.auth import views as auth_views #import this
from signup import views as v

app_name = "main"

urlpatterns = [
    # path('', lambda req: redirect('home/')),
    path('', include('home.urls')),
    path('', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('register/', v.register, name="register"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)


# accounts/password_change/ [name='password_change']
# accounts/password_change/done/ [name='password_change_done']
# accounts/password_reset/ [name='password_reset']
# accounts/password_reset/done/ [name='password_reset_done']
# accounts/reset/<uidb64>/<token>/ [name='password_reset_confirm']
# accounts/reset/done/ [name='password_reset_complete']

home/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import *
from datetime import date


class DateInput(forms.DateInput):
    input_type = 'date' # Сделаем виджет, в котором будет вводиться дата


class CreateNewTutorList(forms.Form):
    class Meta:
        widgets = {
            'date_of_birth': DateInput(),
        }

    name = forms.CharField(label="Имя", max_length=100)
    middle_name = forms.CharField(label="Отчество", max_length=100)
    surname = forms.CharField(label="Фамилия", max_length=100)
    date_of_birth = forms.DateField(label="Дата рождения", widget=DateInput)
    job_exp = forms.IntegerField(label="Стаж")
    user_choice = forms.ModelChoiceField(
        queryset=User.objects.all(),
        widget=forms.Select(attrs={'class': 'custom-select'}),
        label='Пользователь',
    )
    academ = forms.ModelChoiceField(
        queryset=AcademDegree.objects.all(),
        widget=forms.Select(attrs={'class': 'custom-select'}),
        label='Ученая степень',
    )
    job = forms.ModelChoiceField(
        queryset=TeacherJob.objects.all(),
        widget=forms.Select(attrs={'class': 'custom-select'}),
        label='Должность',
    )
    
    def clean(self):
        super(CreateNewTutorList, self).clean()
         
        # Возьмем данные из выбранных ранее сведений
        job_exp = self.cleaned_data.get('job_exp')
        date_of_birth = self.cleaned_data['date_of_birth']
        choosed_user = self.cleaned_data.get('user_choice')

        if Teacher.objects.filter(user_id=choosed_user.id).exists():
            self.errors['user_error'] = self.error_class([
                'Пользователь, которого Вы хотите прикрепить, уже прикреплен к другому преподавателю. Выберите другого пользователя.'])
 
        # Делаем условия на ошибки в зависимости от определенного значения
        if job_exp < 0:
            self.errors['exp_error'] = self.error_class([
                'Стаж не может быть отрицательным числом.'])
        elif job_exp > 100:
            self.errors['exp_error'] = self.error_class([
                'Превышен максимум стажа для данного приложения: 100 лет.'])
        
        print(f"self.calculate_age(date_of_birth) > (int(job_exp): {self.calculate_age(date_of_birth) > (int(job_exp))}")
        print(f"self.calculate_age(date_of_birth) < (int(job_exp) - 21) and (self.calculate_age(date_of_birth) > 0): {self.calculate_age(date_of_birth) < (int(job_exp) - 21) and (self.calculate_age(date_of_birth) > 0)}")
        if self.calculate_age(date_of_birth) < 0:
            self.errors['date_error'] = self.error_class([
                'Дата рождения должна быть раньше, чем нынешнее время.'])
        elif self.calculate_age(date_of_birth) < (int(job_exp) - 21) and (self.calculate_age(date_of_birth) > 0):
            self.errors['date_error'] = self.error_class([
                'Стаж может отсчитываться после трудоустройства, в условия которого необходимо иметь образование не ниже бакалавра.'])
        # return any errors if found
        return self.cleaned_data

    def calculate_age(self, birth_date):
        today = date.today() # Для начала возьмем сегодняшний день
    # Данная булевская переменная проверяет, наступил ли день рождения в этом году или еще нет.
    # Выдает значение 1 (True) или 0 (False).
        one_or_zero = ((today.month, today.day) < (birth_date.month, birth_date.day))
    # Проверяем разность между нынешним годом и годом рождения
        year_difference = today.year - birth_date.year
    # Для полного вычисления возраста вычитаем из разницы между нынешним годом
    # и днем рождения булевскую переменную, которая конвертируется в 1 или 0.
        age = year_difference - one_or_zero
        print(f'Age: {age}')
        return age


class CreateNewWorkload(forms.Form): # Форма назначения учебной нагрузки
    cur_teacher = forms.ModelChoiceField( #Выбор преподавателя
        queryset=Teacher.objects.exclude(is_busy=True), # Исключаем тех преподавателей из списка, которые уже заняты (0 и меньшее количество свободных часов)
        widget=forms.Select(attrs={'class': 'custom-select'}),
        label="Преподаватель"
    )
    cur_subject = forms.ModelChoiceField( # Выбор предмета
        queryset=Subject.objects.all(),
        widget=forms.Select(attrs={'class': 'custom-select'}),
        label='Предметная область'
    )
    cur_group = forms.ModelChoiceField( # Выбор группы студентов
        queryset=GroupClass.objects.all(),
        widget=forms.Select(attrs={'class': 'custom-select'}),
        label='Группа студентов'
    )
    sub_type = forms.ChoiceField( # Выбор вида занятий
        label="Вид занятия",
        choices=SUBJECT_TYPE_CHOICES,
        widget=forms.Select(attrs={'class': 'custom-select'}),
        required=False,
    )

    def clean(self): # Проверка правильности введенных данных
        super(CreateNewWorkload, self).clean()
        current_teacher = self.cleaned_data.get('cur_teacher')
        subject = self.cleaned_data.get('cur_subject')

        if self.check_free_time(current_teacher) < 0: # Если количество свободных часов меньше 0, то выдаст уведомление о выборе другого преподавателя.
            self.errors['free_time_error'] = self.error_class([
                f'Преподаватель {current_teacher.last_name} {current_teacher.first_name} {current_teacher.middle_name} уже занят. Выберите другого.'])
        elif self.check_free_time(current_teacher) < subject.num_of_hours_semester(): # Если предмет по количеству часов больше, чем количество свободных часов преподавателя, то выдаст также уведомление о выборе другого преподавателя.
            self.errors['free_time_error'] = self.error_class([
                f"Преподаватель {current_teacher.last_name} {current_teacher.first_name} {current_teacher.middle_name} не имеет достаточное количество свободных часов - {self.check_free_time(current_teacher)} часов. Выберите другого."
            ])

    def check_free_time(self, teacher): # Проверка на количество свободных часов преподавателя
        free_time = teacher.teacher_job.num_of_hours 
        sub_assigned_set = StudyWorkload.objects.filter(
            teacher_id=teacher.id, 
        ) # Учтем учебную нагрузку, которая была ранее назначена на преподавателя
        for assigned in sub_assigned_set:
            free_time -= assigned.subject.num_of_hours_semester() # Вычисление свободного времени согласно математической модели
        return free_time

        
class ViewProfileForm(forms.Form):
    class Meta:
        widgets = {
            'date_of_birth': DateInput(),
        }

    date_of_birth = forms.DateField(widget=DateInput, label='Дата рождения')
    academ_degrees = forms.ModelChoiceField(
        queryset=AcademDegree.objects.all(),
        label = 'Ученая степень',
        widget=forms.Select(attrs={'class': 'custom-select'})
    )
    t_jobs = forms.ModelChoiceField(
        queryset=TeacherJob.objects.all(),
        label = 'Должность',
        widget=forms.Select(attrs={'class': 'custom-select'})
    )

home/views.py
from datetime import date, datetime

from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.contrib.auth.models import User

from .forms import (
    CreateNewTutorList, CreateNewWorkload, ViewProfileForm
)
from .models import *

@login_required(login_url='/login/') 
def home(response): # Перенаправление на домашнюю страницу
    return render(response, "main/home.html", {"teachers": "Нет информации"})

def teachers_list(response): # Переход на список преподавателей
    t_list = Teacher.objects.all()
    study_list = StudyWorkload.objects.all() 
    for tutor in t_list: # Смотрим информацию по всем преподавателям
        study_list = StudyWorkload.objects.filter(teacher_id=tutor.id)
        if study_list.exists(): # Проверяем, сколько свободных часов у преподавателя еще осталось
            for study in study_list:
                tutor.rest_free_time = study.check_free_time()
        else:            
            tutor.rest_free_time = tutor.teacher_job.num_of_hours
        # Если учебная нагрузка не назначалась ранее, то ставится количество часов, предназначенное
        # по должности согласно математической модели
    return render(response, "main/tutorList.html", {'teachers': t_list})

def create_tutor(response): # Добавление преподавателя
    error_list = []
    if response.method == "POST":
        new_object = CreateNewTutorList(response.POST)
        if new_object.is_valid(): # Проверка правильности ввода полей для добавления преподавателя
            print('Успешно')
            Teacher.objects.create(
                first_name = new_object.cleaned_data["name"],
                last_name = new_object.cleaned_data["surname"],
                academic_degree_id = new_object.cleaned_data["academ"].id,
                teacher_job_id = new_object.cleaned_data["job"].id,
                middle_name=new_object.cleaned_data["middle_name"],
                date_of_birth=new_object.cleaned_data["date_of_birth"],
                job_exp=new_object.cleaned_data["job_exp"],
                user_id=new_object.cleaned_data["user_choice"].id
            )
            return HttpResponseRedirect("/list_of_tutors")
        else: # Если же неправильно введены поля, то приложение выведет уведомление об ошибке
            print('Ошибка 2.')
            print(new_object.cleaned_data)
            print(new_object.errors)
            for field in new_object.errors:    
               error_list.append((new_object.errors[field].as_text())[2::]) # Обработка текста ошибки для уведомлений
            new_object = CreateNewTutorList()
    else:
        new_object = CreateNewTutorList()
    return render(response, "create/tutor.html", { # Выходим на страницу списка преподавателей 
        'form': new_object, 
        'error_list': error_list, # Список ошибок 
        'count': len(error_list), # Количество ошибок
    })

def study_work_list(response): # Учебная нагрузка
    if response.user.is_superuser: # Для администратора показывается вся учебная нагрузка
        work_list = StudyWorkload.objects.all()
    else: # Если же нет прав администратора, то выводится информация о учебной нагрузке преподавателя
        try:
            current_teacher = Teacher.objects.get(user_id=response.user.id)
            work_list = StudyWorkload.objects.filter(teacher_id=current_teacher.id)
        except: 
            work_list = []
    return render(response, "main/workList.html", {'work': work_list})

def create_workload(response): # Назначение учебной нагрузки
    error_list = []
    if response.method == "POST":
        new_object = CreateNewWorkload(response.POST)
        if new_object.is_valid():
            cur_teacher = new_object.cleaned_data["cur_teacher"]
            cur_subject = new_object.cleaned_data["cur_subject"]
            cur_group = new_object.cleaned_data["cur_group"]
            cur_sub_type = new_object.cleaned_data["sub_type"]
            StudyWorkload.objects.create( # Назначение учебной нагрузки на учителя
                teacher_id=cur_teacher.id,
                subject_id=cur_subject.id,
                group_id=cur_group.id,
                sub_type=cur_sub_type,
            )
            return HttpResponseRedirect("/list_of_work")
        else:   
            for field in new_object.errors: # Вывод ошибок в случае некорректности введенных данных
               error_list.append((new_object.errors[field].as_text())[2::])
            new_object = CreateNewWorkload()
    else:
        new_object = CreateNewWorkload()
    return render(response, "create/workload.html", {
        'form': new_object,
        'error_list': error_list, 
    })

def delete_workload(response, id):
    work = get_object_or_404(StudyWorkload, id=id)  # При нажатии на "карточку" с нагрузкой выбирается определенная нагрузка.

    if response.method == 'POST':        # Если кнопка была нажата,
        work.delete()                     # то преподаватель освобождается от учебной нагрузки (количество свободных часов увеличится).
        work.check_free_time()
        return HttpResponseRedirect('/list_of_work/') # В конце переходим на начальную страницу "Учебная нагрузка".

    return render(response, 'main/workList.html', {'work': work})

def get_profile_info(response): # Страница личного профиля
    isUserTeacher = False 
    view_info = ViewProfileForm(response.GET)
    current_user_info = User.objects.get(id=response.user.id)
    academ_list = AcademDegree.objects.all()
    teacher_job_list = TeacherJob.objects.all()
    current_teach_info = None
    try:
        current_teach_info = Teacher.objects.get(user_id=current_user_info.id)
        view_info = ViewProfileForm(initial = {
            'date_of_birth': current_teach_info.date_of_birth if current_teach_info.date_of_birth else None,
            'academ_degrees': current_teach_info.academic_degree.id if current_teach_info.academic_degree else None, 
            't_jobs': current_teach_info.teacher_job.id if current_teach_info.teacher_job else None
        })
        isUserTeacher = True
    except Teacher.DoesNotExist:
        current_teach_info = None
    return render(response, "main/profile.html", {
        'form': view_info,
        'isThatUserTeacher': isUserTeacher,
        'user_info': current_user_info,
        'work_info': current_teach_info,
        'academ_dropdown_list': academ_list,
        'teacher_job_dropdown_list': teacher_job_list, 
    })

def save_changed_profile_info(response):
    if response.method == "POST":
        my_email = response.POST.get("email", "") 
        User.objects.filter(id=response.user.id).update(
            email=my_email,
        )
        profile_info = ViewProfileForm(response.POST)
        if profile_info.is_valid():
            if Teacher.objects.filter(user_id=response.user.id).exists():
                Teacher.objects.filter(user_id=response.user.id).update(
                    first_name = response.POST.get("name", ""),
                    last_name = response.POST.get("surname", ""),
                    middle_name = response.POST.get("middle_name", ""),
                    phone_number = response.POST.get("phone_number", ""),
                    academic_degree = profile_info.cleaned_data["academ_degrees"].id,
                    teacher_job = profile_info.cleaned_data["t_jobs"].id,
                    date_of_birth = profile_info.cleaned_data["date_of_birth"],
                    location = response.POST.get("location", ""),
                )
        return HttpResponseRedirect('/profile/')
    else:
        profile_info = ViewProfileForm()
    return render(response, "create/workload.html", {'form': profile_info})

def info(response):
    return render(response, "main/instruction.html", {})

home/templates/main/base.html
<!DOCTYPE html>
<html lang="ru">
    <head>
        <style type="text/css">
            .sidenav {
                height: 100%;
                width: 240px;
                position: fixed;
                z-index:1;
                top:0;
                left:0;
                background-color: #026670;
                overflow-x: hidden;
                padding-top: 20px;
            }

            .topbar {
                height: 55px;
                width: 90%;
                position: fixed;
                z-index:1;
                top: 0;
                left: 240px;
                background-color: #2B7a78;
            }

            .sidenav a {
                padding: 6px 8px 6px 16px;
                text-decoration: none;
                font-size: 18px;
                color: #FCE181;
                display: block;
            }

            .sidenav a:hover{
                color: #FEF9C7;
            }

            .sidenav p {
                padding: 6px 8px 6px 16px;
                text-decoration: none;
                font-size: 18px;
                color: #FCE181;
                display: block;
            }

            .main{
                margin-top: 60px;
                margin-left:240px;
                padding: 0px 10px;
            }

            p, a, h1, h4 {
                color:#026670;
            }
        </style>

        {% load rest_framework %}
        {% load widget_tweaks %}
        {% load static %}

        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" crossorigin="anonymous" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" rel="stylesheet"/>
        <title>{% block title %}Распределение учебной нагрузки{% endblock %}</title>
    </head>
    <body>
        {% if user.is_authenticated %}

        <div class="topbar">
            <!-- <div class="row align-items-center justify-content-end"> -->
                <!-- {% if user.is_authenticated %} -->
                    <div class="dropdown d-flex justify-content-end align-items-center" style="margin-right: 6.5em;">
                        <a class="btn btn-info dropdown-toggle mt-2" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                          Профиль: {{ user }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="dropdownMenuLink">
                            <a class="dropdown-item" href="{% url 'home:myAccount' %}">Мой профиль</a>
                            {% if user.is_superuser %}
                                <a class="dropdown-item" href="{% url 'admin:index' %}">Админ-панель</a>
                            {% endif %}
                            <hr class="dropdown-divider">
                            <a class="dropdown-item" href="{% url 'logout' %}">Выйти</a>
                          <!-- <a class="dropdown-item" href="#">Action</a>
                          <a class="dropdown-item" href="#">Another action</a>
                          <a class="dropdown-item" href="#">Something else here</a> -->
                        </div>
                    </div>
                    <!-- <p class="col-md-4 offset-md-4">Привет, {{ user }}!</p>
                    <a class="col-4" href="{% url 'logout' %}">Выйти</a> -->
                <!-- {% else %}
                    <p class="col">Войдите, пожалуйста!</p>
                {% endif %} -->
            <!-- </div> -->
        </div>
        {% endif %}


        <div class="sidenav">
            {% if user.is_authenticated %}
                <div style="text-align: -webkit-center;">
                    <img class="w-25 h-5" src="{% static 'images/user.png' %}">
                </div>
                <a href="{% url 'home:home' %}">Домашняя страница</a>
                <a href="{% url 'home:teacherList' %}">Список преподавателей</a>
                <a href="{% url 'home:workList' %}">Учебная нагрузка</a>
                <a href="{% url 'home:info' %}">Инструкция</a>
            {% endif %}  
            <!-- {% if user.is_authenticated %}
                <p>Привет, {{ user }}!</p>
                <a href="{% url 'logout' %}">Выйти</a>
            {% else %}
                <p>Войдите, пожалуйста!</p>
            {% endif %} -->
        </div>

        <div id="content", name="content", class="main">
            <div class="row justify-content-center">
                <div class="col-8 mt-4">
                    <!-- {% if user.is_superuser %}
                        <h1 class="mt-2">Мое приложение</h1>
                        <hr class="mt-0 mb-4">
                    {% endif %} -->
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
        <script src="{% static 'js/success_alert.js' %}"></script>
        <script src="https://code.jquery.com/jquery-3.2.1.min.js" crossorigin="anonymous" integrity="sha384-xBuQ/xzmlsLoJpyjoggmTEz8OWUFM0/RC5BsqQBDX2v5cMvDHcMakNTNrHIW2I5f"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" crossorigin="anonymous" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" crossorigin="anonymous" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"></script>
        <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script> -->
    </body>
</html>

home/templates/main/home.html
{% extends 'main/base.html' %}

{% block content %}
<h1>Домашняя страница</h1>
<div>
    <p>Данное приложение предназначено для распределения учебной нагрузки.</p>
    <p>Разработано Скрыпником Иван Владимировичем, студентом 1181б, ЮГУ. © 2022</p>
    <p>По всем вопросам обращайтесь на mayrocken@gmail.com</p>
</div>
{% endblock %}

home/templates/main/instruction.html
{% extends 'main/base.html' %}
{% load static %}

{% block content %}
<h1>Инструкция</h1>
<h2>Что же делать в этой программе?</h2>
<p>Главная задача данного приложения - распределение учебной нагрузки.</p>
<br>
<h2>Как определить учебную нагрузку кому-либо?</h2>
<ol>
    <img src="{% static 'images/info/get_work_1.png' %}">
    <li>
        <p>Необходимо зайти на страницу "Учебная нагрузка".</p>
    </li>
    <img style="height: 150px; width: 500px;" src="{% static 'images/info/get_work_2.png' %}">
    <li>
        <p>Если вы обладаете правами администратора, то нажмите на кнопку "Назначить учебную нагрузку".</p>
    </li>
    <img style="height: 250px; width: 500px;" src="{% static 'images/info/get_work_3.png' %}">
    <li>
        <p>Заполните формы.</p>
    </li>
    <img style="height: 230px; width: 500px;" src="{% static 'images/info/get_work_4.png' %}">
    <li>
        <p>После этого проверьте, что новая карточка с информацией по нагрузке добавилась.</p>
    </li>
</ol>
{% endblock %}

home/templates/main/tutorList.html
{% extends "main/base.html" %}
{% load rest_framework %}

{% block title %}Текущий список преподавателей{% endblock %}

{% block content %}
    <h1>Список преподавателей:</h1> 
    <div class="input-group mb-3">
        <table class="table table-striped">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">ФИО</th>
                    <th scope="col">Имя пользователя</th>
                    <th scope="col">Дата рождения</th>
                    <th scope="col">Стаж</th>
                    <th scope="col">Ученая степень</th>
                    <th scope="col">Должность</th>
                    <th scope="col">Кол-во свободных часов</th>
                    <th scope="col">Осталось</th>
                </tr>
            </thead>
            <tbody>
                {% if teachers %}
                    {% for tutor in teachers %}
                    <tr>
                        <th scope="row">{{ tutor.id }}</th>
                        <td>{{ tutor.first_name }} {{tutor.middle_name }} {{ tutor.last_name }}</td>
                        {% if tutor.user.username %}
                            <td>{{ tutor.user.username }}</td>
                        {% else %}
                            <td>Нет пользователя</td>
                        {% endif %}
                        <td>{{ tutor.date_of_birth }}</td>
                        <td>{{ tutor.job_exp }}</td>
                        <td>{{ tutor.academic_degree.name }}</td>
                        <td>{{ tutor.teacher_job.name }}</td>
                        <td>{{ tutor.teacher_job.num_of_hours }} ч.</td> 
                        <td>{{ tutor.rest_free_time }} ч.</td>
                    </tr>
                    {% endfor %}
                {% else %}
                    <p>Нет информации.</p>
                {% endif %}
            </tbody>
        </table>   
    </div>
    {% if user.is_superuser %}
        <input type="button", onclick="window.location.href='{% url 'home:createTutor' %}'", class="btn btn-primary", value="Создать">
    {% endif %}
{% endblock %}

home/templates/main/workList.html
{% extends "main/base.html" %}
{% load rest_framework %}

{% block title %}Учебная нагрузка{% endblock %}

{% block content %}
    {% if user.is_superuser %}
        <h1>Общая учебная нагрузка:</h1>
    {% else %}
        <h1>Моя учебная нагрузка:</h1>
    {% endif %}
    <div class="input-group mb-3">
    {% if work %}    
        {% for one in work %}
            <div class="card w-100 mt-2 mb-2">
                <div class="card-header bg-info d-flex justify-content-between">
                    <div class="text-white">
                        Информация
                    </div>
                    {% if user.is_superuser %}
                        <form action="{% url 'home:deleteWork' one.id %}" method="post">
                            {% csrf_token %}
                            <button type="submit" class="btn-close" aria-label="Close"></button>
                        </form>
                    {% endif %}
                </div>
                <div class="card-body">
                  <h4 class="card-title">{{one.teacher.last_name}} {{one.teacher.first_name}} {{one.teacher.middle_name}}</h4>
                  <p style="font-size: 12px;">{{ one.teacher.academic_degree.name }}, {{ one.teacher.teacher_job.name }}</p>
                  <p class="card-text">Предмет: {{one.subject}}</p>
                  <p class="card-text">Вид занятия: {{one.sub_type}}</p>
                  <p class="card-text">Группа: {{one.group}}</p>
                </div>
            </div>    
        {% endfor %}
    {% else %}
        {% if user.is_superuser %}
            <p>Ни у кого из преподавателей нет учебной нагрзуки. Назначьте, пожалуйста.</p>
        {% else %}
            <p>На данный момент у Вас нет учебной нагрузки.</p>
        {% endif %}
    {% endif %}
    </div>
    {% if user.is_superuser %}
        <input type="button", onclick="window.location.href='{% url 'home:createWork' %}'", class="btn btn-primary", value="Дать учебную нагрузку">
    {% endif %}
{% endblock %}